name = "FastOPInterpolation"
uuid = "7decf2fc-1b41-4df3-8d24-d8c3407cdb84"
authors = ["Nicolas Wink <nicolas.wink@tu-darmstadt.de>", "Eduardo Grossi"]
version = "0.1.0"

[deps]
Kronecker = "2c470bb0-bcc8-11e8-3dad-c9649493f05e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
